<?php

declare(strict_types=1);


namespace AmazonPHP\SellingPartner\Model\FulfillmentInbound;

use \ArrayAccess;
use \AmazonPHP\SellingPartner\ObjectSerializer;
use \AmazonPHP\SellingPartner\ModelInterface;
use \AmazonPHP\SellingPartner\Exception\AssertionException;

/**
* The Selling Partner API for FBA inbound operations.
*
* The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
*
* The version of the OpenAPI document: 2024-03-20
*
* This class was auto-generated by https://openapi-generator.tech
* Do not change it, it will be overwritten with next execution of /bin/generate.sh
 *
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class BoxContent implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'BoxContent';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static array $openAPITypes = [
        'expiration' => 'string',
        'label_owner' => '\AmazonPHP\SellingPartner\Model\FulfillmentInbound\LabelOwner',
        'manufacturing_lot_code' => 'string',
        'msku' => 'string',
        'prep_owner' => '\AmazonPHP\SellingPartner\Model\FulfillmentInbound\PrepOwner',
        'quantity_in_box' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'expiration' => null,
        'label_owner' => null,
        'manufacturing_lot_code' => null,
        'msku' => null,
        'prep_owner' => null,
        'quantity_in_box' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes() : array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats() : array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static array $attributeMap = [
        'expiration' => 'expiration',
        'label_owner' => 'labelOwner',
        'manufacturing_lot_code' => 'manufacturingLotCode',
        'msku' => 'msku',
        'prep_owner' => 'prepOwner',
        'quantity_in_box' => 'quantityInBox'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static array $setters = [
        'expiration' => 'setExpiration',
        'label_owner' => 'setLabelOwner',
        'manufacturing_lot_code' => 'setManufacturingLotCode',
        'msku' => 'setMsku',
        'prep_owner' => 'setPrepOwner',
        'quantity_in_box' => 'setQuantityInBox'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static array $getters = [
        'expiration' => 'getExpiration',
        'label_owner' => 'getLabelOwner',
        'manufacturing_lot_code' => 'getManufacturingLotCode',
        'msku' => 'getMsku',
        'prep_owner' => 'getPrepOwner',
        'quantity_in_box' => 'getQuantityInBox'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap() : array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters() : array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters() : array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName() : string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['expiration'] = $data['expiration'] ?? null;
        $this->container['label_owner'] = $data['label_owner'] ?? null;
        $this->container['manufacturing_lot_code'] = $data['manufacturing_lot_code'] ?? null;
        $this->container['msku'] = $data['msku'] ?? null;
        $this->container['prep_owner'] = $data['prep_owner'] ?? null;
        $this->container['quantity_in_box'] = $data['quantity_in_box'] ?? null;
    }

    /**
     * Validate all properties.
     *
     * @throws AssertionException
     */
    public function validate() : void
    {
        if (!is_null($this->container['expiration']) && !preg_match("/^([0-9]{4})-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$/", $this->container['expiration'])) {
            throw new AssertionException("invalid value for 'expiration', must be conform to the pattern /^([0-9]{4})-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$/.");
        }

        if ($this->container['label_owner'] === null) {
            throw new AssertionException("'label_owner' can't be null");
        }

        if (!is_null($this->container['manufacturing_lot_code']) && (mb_strlen($this->container['manufacturing_lot_code']) > 256)) {
            throw new AssertionException("invalid value for 'manufacturing_lot_code', the character length must be smaller than or equal to 256.");
        }

        if (!is_null($this->container['manufacturing_lot_code']) && (mb_strlen($this->container['manufacturing_lot_code']) < 1)) {
            throw new AssertionException("invalid value for 'manufacturing_lot_code', the character length must be bigger than or equal to 1.");
        }

        if ($this->container['msku'] === null) {
            throw new AssertionException("'msku' can't be null");
        }

        if ((mb_strlen($this->container['msku']) > 40)) {
            throw new AssertionException("invalid value for 'msku', the character length must be smaller than or equal to 40.");
        }

        if ((mb_strlen($this->container['msku']) < 1)) {
            throw new AssertionException("invalid value for 'msku', the character length must be bigger than or equal to 1.");
        }

        if ($this->container['prep_owner'] === null) {
            throw new AssertionException("'prep_owner' can't be null");
        }

        if ($this->container['quantity_in_box'] === null) {
            throw new AssertionException("'quantity_in_box' can't be null");
        }

        if (($this->container['quantity_in_box'] > 10000)) {
            throw new AssertionException("invalid value for 'quantity_in_box', must be smaller than or equal to 10000.");
        }

        if (($this->container['quantity_in_box'] < 1)) {
            throw new AssertionException("invalid value for 'quantity_in_box', must be bigger than or equal to 1.");
        }

    }


    /**
     * Gets expiration
     *
     * @return string|null
     */
    public function getExpiration()
    {
        return $this->container['expiration'];
    }

    /**
     * Sets expiration
     *
     * @param string|null $expiration The date in ISO 8601 format for when the MSKU expires.
     *
     * @return self
     */
    public function setExpiration($expiration) : self
    {
        $this->container['expiration'] = $expiration;

        return $this;
    }

    /**
     * Gets label_owner
     *
     * @return \AmazonPHP\SellingPartner\Model\FulfillmentInbound\LabelOwner
     */
    public function getLabelOwner()
    {
        return $this->container['label_owner'];
    }

    /**
     * Sets label_owner
     *
     * @param \AmazonPHP\SellingPartner\Model\FulfillmentInbound\LabelOwner $label_owner label_owner
     *
     * @return self
     */
    public function setLabelOwner($label_owner) : self
    {
        $this->container['label_owner'] = $label_owner;

        return $this;
    }

    /**
     * Gets manufacturing_lot_code
     *
     * @return string|null
     */
    public function getManufacturingLotCode()
    {
        return $this->container['manufacturing_lot_code'];
    }

    /**
     * Sets manufacturing_lot_code
     *
     * @param string|null $manufacturing_lot_code The manufacturing lot code.
     *
     * @return self
     */
    public function setManufacturingLotCode($manufacturing_lot_code) : self
    {
        $this->container['manufacturing_lot_code'] = $manufacturing_lot_code;

        return $this;
    }

    /**
     * Gets msku
     *
     * @return string
     */
    public function getMsku()
    {
        return $this->container['msku'];
    }

    /**
     * Sets msku
     *
     * @param string $msku The merchant SKU, a merchant-supplied identifier for a specific SKU.
     *
     * @return self
     */
    public function setMsku($msku) : self
    {
        $this->container['msku'] = $msku;

        return $this;
    }

    /**
     * Gets prep_owner
     *
     * @return \AmazonPHP\SellingPartner\Model\FulfillmentInbound\PrepOwner
     */
    public function getPrepOwner()
    {
        return $this->container['prep_owner'];
    }

    /**
     * Sets prep_owner
     *
     * @param \AmazonPHP\SellingPartner\Model\FulfillmentInbound\PrepOwner $prep_owner prep_owner
     *
     * @return self
     */
    public function setPrepOwner($prep_owner) : self
    {
        $this->container['prep_owner'] = $prep_owner;

        return $this;
    }

    /**
     * Gets quantity_in_box
     *
     * @return int
     */
    public function getQuantityInBox()
    {
        return $this->container['quantity_in_box'];
    }

    /**
     * Sets quantity_in_box
     *
     * @param int $quantity_in_box The number of units of the given MSKU in the box.
     *
     * @return self
     */
    public function setQuantityInBox($quantity_in_box) : self
    {
        $this->container['quantity_in_box'] = $quantity_in_box;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @return boolean
     */
    public function offsetExists($offset) : bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @return void
     */
    public function offsetSet($offset, $value) : void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @return void
     */
    public function offsetUnset($offset) : void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize() : string
    {
       return \json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString() : string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue() : string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

