<?php

declare(strict_types=1);

namespace AmazonPHP\SellingPartner\Model\FulfillmentInbound;

/**
 * Selling Partner API for Fulfillment Inbound.
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * The version of the OpenAPI document: v0
 *
 * This class was auto-generated by https://openapi-generator.tech
 * Do not change it, it will be overwritten with next execution of /bin/generate.sh
 */
class PackageStatus
{
    /**
     * Possible values of this enum.
     */
    final public const SHIPPED = 'SHIPPED';

    final public const IN_TRANSIT = 'IN_TRANSIT';

    final public const DELIVERED = 'DELIVERED';

    final public const CHECKED_IN = 'CHECKED_IN';

    final public const RECEIVING = 'RECEIVING';

    final public const CLOSED = 'CLOSED';

    final public const DELETED = 'DELETED';

    public function __construct(private readonly string $value)
    {
    }

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues() : array
    {
        return [
            self::SHIPPED,
            self::IN_TRANSIT,
            self::DELIVERED,
            self::CHECKED_IN,
            self::RECEIVING,
            self::CLOSED,
            self::DELETED,
        ];
    }

    public function toString() : string
    {
        return $this->value;
    }
}
