<?php

declare(strict_types=1);

namespace AmazonPHP\SellingPartner\Model\FulfillmentInbound;

/**
 * Selling Partner API for Fulfillment Inbound.
 *
 * The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
 *
 * The version of the OpenAPI document: v0
 *
 * This class was auto-generated by https://openapi-generator.tech
 * Do not change it, it will be overwritten with next execution of /bin/generate.sh
 */
class SellerFreightClass
{
    /**
     * Possible values of this enum.
     */
    final public const _50 = '50';

    final public const _55 = '55';

    final public const _60 = '60';

    final public const _65 = '65';

    final public const _70 = '70';

    final public const _77_5 = '77.5';

    final public const _85 = '85';

    final public const _92_5 = '92.5';

    final public const _100 = '100';

    final public const _110 = '110';

    final public const _125 = '125';

    final public const _150 = '150';

    final public const _175 = '175';

    final public const _200 = '200';

    final public const _250 = '250';

    final public const _300 = '300';

    final public const _400 = '400';

    final public const _500 = '500';

    public function __construct(private readonly string $value)
    {
    }

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues() : array
    {
        return [
            self::_50,
            self::_55,
            self::_60,
            self::_65,
            self::_70,
            self::_77_5,
            self::_85,
            self::_92_5,
            self::_100,
            self::_110,
            self::_125,
            self::_150,
            self::_175,
            self::_200,
            self::_250,
            self::_300,
            self::_400,
            self::_500,
        ];
    }

    public function toString() : string
    {
        return $this->value;
    }
}
