<?php

declare(strict_types=1);


namespace AmazonPHP\SellingPartner\Model\FulfillmentInbound;
use \AmazonPHP\SellingPartner\ObjectSerializer;
use \AmazonPHP\SellingPartner\ModelInterface;
use \AmazonPHP\SellingPartner\Exception\AssertionException;

/**
* Selling Partner API for Fulfillment Inbound
*
* The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.
*
* The version of the OpenAPI document: v0
*
* This class was auto-generated by https://openapi-generator.tech
* Do not change it, it will be overwritten with next execution of /bin/generate.sh
 */
class TransportStatus
{
    /**
     * Possible values of this enum
     */
    const WORKING = 'WORKING';

    const ESTIMATING = 'ESTIMATING';

    const ESTIMATED = 'ESTIMATED';

    const ERROR_ON_ESTIMATING = 'ERROR_ON_ESTIMATING';

    const CONFIRMING = 'CONFIRMING';

    const CONFIRMED = 'CONFIRMED';

    const ERROR_ON_CONFIRMING = 'ERROR_ON_CONFIRMING';

    const VOIDING = 'VOIDING';

    const VOIDED = 'VOIDED';

    const ERROR_IN_VOIDING = 'ERROR_IN_VOIDING';

    const ERROR = 'ERROR';

    private string $value;

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::WORKING,
            self::ESTIMATING,
            self::ESTIMATED,
            self::ERROR_ON_ESTIMATING,
            self::CONFIRMING,
            self::CONFIRMED,
            self::ERROR_ON_CONFIRMING,
            self::VOIDING,
            self::VOIDED,
            self::ERROR_IN_VOIDING,
            self::ERROR
        ];
    }

    public function __construct(string $value)
    {
        $this->value = $value;
    }

    public function toString(): string
    {
        return $this->value;
    }
}

