generatorName: php
templateDir: sp-api/resources/php-amazon-selling-partner-api
additionalProperties:
  invokerPackage: AmazonPHP\SellingPartner
  srcBasePath: src/AmazonPHP/SellingPartner
  modelPackage: Model\ProductTypesDefinitions
  packageName: ProductTypesDefinitions
files:
  api.mustache:
    templateType: API
    destinationFilename: /ProductTypesDefinitionsSDK.php
  api_interface.mustache:
    templateType: API
    destinationFilename: /ProductTypesDefinitionsSDKInterface.php