name: "Update Models"

on:
  workflow_dispatch:
#  schedule:
#    - cron:  '0 8 * * *'

jobs:
  update-models:
    name: "Update Models"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "7.4"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          tools: composer:v2
          php-version: "7.4"
          ini-values: memory_limit=-1

      - name: "Cache dependencies"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.composer/cache
            vendor
          key: "php-7.4-locked"
          restore-keys: "php-7.4"

      - name: "Install locked dependencies"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: "Update SDK Models"
        run: "composer generate"

      - name: "Git status"
        run: "git status"

      - name: "Create Pull Request"
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Updated SDK Models"
          committer: "GitHub <noreply@github.com>"
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update/sdk-models
          title: "Updated SDK Models"

      - name: "Check output"
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"